events { 
    worker_connections 1024; 
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # 1. USMERJANJE ZA FRONTEND (Blazor WASM statične datoteke)
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html =404;
        }

        # 2. PROXIRANJE ZA BACKEND (Nginx preusmeri klice na .NET API znotraj Dockerja)
        location /api/ {
            resolver 127.0.0.11 valid=5s;
            proxy_pass http://todoapp.webapi:8080/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}